### ISSUE TITLE
allow OMIM: prefix in the omim_id of the hpo/omims endpoint

### ISSUE THREAD

**Issue by stolpeo** [varfish-org/viguno#178]
**Is your feature request related to a problem? Please describe.**

Currently, OMIM and MIM terms are only accepted without the prefix (i.e. just the digits) in the endpoint `/hpo/omims`. Make the endpoint consistent with the HPO terms endpoint that accepts the `HP:` prefix by allowing the `OMIM:` / `MIM:` prefix and stripping it, i.e. allow queries like `/hpo/omims?omim_id=OMIM:616145`.

**Comment by holtgrewe** [comment]
cf. varfish-org/varfish-server#1792
